Organisms header
AyumuTaoka/a.taoka-frontend-basic-last-assignment pull request #13
Opened 2022-06-28 17:12 UTC by AyumuTaoka

## セルフチェック
- [O] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [O] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [O] 記述の重複はないか

リンク
[https://626e03ce97ce92004af16925-wxwtejxdqi.chromatic.com/?path=/story/organisms-header--header](chromatic上の該当ページへのリンクを貼る)

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.html
> +<div class="hearder_wrapper">
headerタグを使いましょう！

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +  & .navbar {
ここの高さがfigmaと違います

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            transition: 0.2s ease;
ホバー前とホバー後で色が変わらないのであればこれは必要ないと思います

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +        & > li:last-child {
これは必要ですか？

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +    & > .navbar-brand {
画面幅XL以上の時のロゴの大きさが違います

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +        & > li:nth-child(2) {
ここだけ他のliと高さが違うので揃えてください！

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            float: right;
floatはなるべく使わないようにしましょう。横並びは基本的にフレックスボックスを使います。

2022-06-29 15:41 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            & > a {
ここの高さがfigmaと違います。それと、フォントサイズが違うと思います。
ブログアーカイブだけpaddingが他と違うのでそこの修正もお願いします...!
![スクリーンショット (164)](https://user-images.githubusercontent.com/83950556/176476769-9ea0cf97-aaaf-47d7-afe2-22f919038893.png)

2022-06-30 07:10 UTC, AyumuTaoka commented on src/components/organisms/header/header.scss
> +            transition: 0.2s ease;
以下のスクショのように、元からホバーすると色が変わるようになっていたため、これを書きました。
<img width="1440" alt="スクリーンショット 2022-06-30 16 07 24" src="https://user-images.githubusercontent.com/104242534/176614777-209ae0e6-1159-4c0b-ad98-3a59cd306b49.png">

2022-06-30 07:11 UTC, AyumuTaoka commented on src/components/organisms/header/header.scss
> +        & > li:last-child {
すいません、消し忘れてました

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            padding: 15px 0;
クリックできる範囲(縦幅)が狭いと思います。灰色の部分全てクリックできるようにした方がいいです。

![スクリーンショット (169)](https://user-images.githubusercontent.com/83950556/177002360-f5415f72-f4fc-44a4-9934-1bc2f7094575.png)

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +        height: 20.56px;
figmaの厳密な値でなくてよいので整数値で書いてください

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            padding: 35px 20px;
breakpoint-xl以上のときのヘッダーの高さがfigmaと違います

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +              padding: 15px 12px;
breakpoint-xl以上のときpaddingの値変わります

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +      ul {
全体的に言えることですが、HTML要素名ではなくてクラス名で書いてほしいです！

2022-07-02 13:31 UTC, minezaki-mutsuki commented on src/components/organisms/header/header.scss
> +            font-weight: 400;
デフォルトで400なので書かなくてもよいと思います

2022-07-06 00:27 UTC, KEISUKE0293 reviewed
![image](https://user-images.githubusercontent.com/88794030/177437839-ed7acf28-fb71-4e6f-afcb-7f9324a10168.png)
ここの横幅が短いのでfigma通りに直してください！

2022-07-09 03:29 UTC, Ravie403 requested changes
全体的によくできていますが、typoの修正を数個よろしくお願いします。

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +<header class="hearder_wrapper">
```suggestion
<header class="header-wrapper">
```
クラス名は原則としてスネークケース(_でつなげる)ではなくケバブケース(-でつなげる)でお願いします。

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +      class="navbar-toggler btn hanburger-btn"
```suggestion
      class="navbar-toggler btn hamburger-btn"
```

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +      <img class="hamburger" src="./img/humberger-icon.svg" alt="" />
```suggestion
      <img class="hamburger" src="./img/hamburger-icon.svg" alt="" />
```

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +          <div class="conseptBtn-wraper">
```suggestion
          <div class="conceptBtn-wrapper">
```

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +            id="collapseExample"
id名は`collapseExample`だと具体性に欠けるので具体性を持たせるとよいです
e.g. collapse-concept など。

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.html
> +          <a class="nav-link" href="#">DOWNLORD</a>
```suggestion
          <a class="nav-link" href="#">DOWNLOAD</a>
```

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.scss
> +            font-size: $fontsize-s;
font-familyも設定してください（figmaで指定されているので）

2022-07-09 03:29 UTC, Ravie403 commented on src/components/organisms/header/header.scss
> +.hearder_wrapper {
上の修正を反映する場合こちらも忘れずにお願いします。

2022-07-09 05:53 UTC, MoAI522 approved these changes
LGTM

2022-07-09 05:53 UTC, merged